# Fetching the latest node image on apline linux
FROM node:18-alpine AS builder

# Declaring env
ENV NODE_ENV production

# Setting up the work directory
WORKDIR /my-story-reactjs-app

# Installing dependencies
COPY ./package.json ./
COPY ./yarn.lock ./

# rebuild node-sass
# RUN yarn add node-sass

RUN yarn install

# Copying all the files in our project to working dir
COPY . .

# Building our application
RUN yarn run build

# Fetching the latest nginx image
FROM nginx

# Creating a the folder sunbuy.vn to contain landing page assets
RUN mkdir -p /usr/share/nginx/html/truyenfun.vn

# Copying built assets from builder
COPY --from=builder /my-story-reactjs-app/out /usr/share/nginx/html/truyenfun.vn

# Copying our nginx.conf
COPY truyenfun.vn.nginx.conf /etc/nginx/conf.d/default.conf
